# In the event some third party modules uses local exec, we may need to install some custom libraries on top of the default terraform container. We can define that here if and when it's needed

FROM hashicorp/terraform:0.12.20

#At this point, no additional ,libraries are needed